language: c
compiler: gcc
install:
  - sudo modprobe msr
before_install:
  - git clone https://github.com/RRZE-HPC/likwid likwid
dist: trusty
sudo: required
script:
  - cd likwid && make && sudo make install && cd ..
  - likwid-perfctr -V 3 -C 0 -g L2 hostname
