language: c
compiler: gcc
install:
  - sudo modprobe msr
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y msr-tools
dist: trusty
sudo: required
script:
  - make
  - ls -la /dev/cpu/0/msr
  - uname -a
  - cat /proc/cpuinfo
  - cat /proc/cpuinfo | grep -i msr | head -n 1
  - ./test-msr-access
  - sudo ./test-msr-access
  - sudo bash -c "./test-msr-access"
  - sudo chown root:root test-msr-access
  - sudo chmod u+s test-msr-access
  - ./test-msr-access
  - rdmsr -p0 0x38D
  - wrmsr -p0 0x38D 0
  - sudo rdmsr -p0 0x38D
  - sudo wrmsr -p0 0x38D 0
